/*
 * mallocexerc01.c
 *
 *  Created on: 11 de nov. de 2021
 *      Author: ernani
 */

/*
	UM ARQUIVO TEXTO CONTÉM UMA SÉRIE DE COORDENADAS X E Y DE PONTOS NA
	SUPERFÍCIE DE MARTE. NO MÁXIMO O ARQUIVO CONTERÁ 10000 DE PONTOS (PARES DE COORDENADAS).
	NO ARQUIVO, AS COORDENADAS X E Y ESTÃO NA MESMA LINHA, SEPARADAS POR ESPAÇO.

	CONSTRUA UM PROGRAMA C QUE PROCESSE O ARQUIVO DE PONTOS 1 LINHA POR VEZ.
	AO FINAL, O PROGRAMA DEVE EXIBIR A DISTÂNCIA TOTAL DA TRAJETÓRIA REPRESENTADA
	PELOS PONTOS LIDOS.
	OS PONTOS DEVEM SER ARMAZENADOS E PROCESSADOS EM UM VETOR DE STRUCTS DINÂMICAS.
	AO FINAL DO PROGRAMA, TODA A MEMÓRIA DINÂMICA DEVE SER LIBERADA.

	EXEMPLO DO CONTEÚDO DO ARQUIVO:
			12 34
			56 125
			67 89
			etc..
*/

raiz quadrada((56-12)**2 + (125-34)**2)




